version: '3.8'

services:

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - SECRET_KEY=supersecretkey123
      - SQLALCHEMY_DATABASE_URI=postgresql://auth_user:auth_pass@auth_db:5432/auth_db
    depends_on:
      - auth_db
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5002:5002"
    environment:
      - SECRET_KEY=supersecretkey123
      - SQLALCHEMY_DATABASE_URI=postgresql://user_user:user_pass@user_db:5432/user_db
    depends_on:
      - auth-service
      - user_db
    restart: unless-stopped

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5003:5003"
    environment:
      - SECRET_KEY=supersecretkey123
      - SQLALCHEMY_DATABASE_URI=postgresql://product_user:product_pass@product_db:5432/product_db
    depends_on:
      - product_db
    restart: unless-stopped

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "5004:5004"
    environment:
      - SECRET_KEY=supersecretkey123
      - SQLALCHEMY_DATABASE_URI=postgresql://cart_user:cart_pass@cart_db:5432/cart_db
    depends_on:
      - cart_db
      - auth-service
      - product-service
    restart: unless-stopped

  auth_db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  user_db:
    image: postgres:13
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  product_db:
    image: postgres:13
    container_name: product_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    volumes:
      - product_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  cart_db:
    image: postgres:13
    container_name: cart_db
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_pass
    volumes:
      - cart_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  auth_db_data:
  user_db_data:
  product_db_data:
  cart_db_data:
