version: '3.8'

services:

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - SECRET_KEY=supersecretkey123
      - SQLALCHEMY_DATABASE_URI=postgresql://auth_user:auth_pass@auth_db:5432/auth_db
    depends_on:
      - auth_db

  auth_db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - SECRET_KEY=supersecretkey123
      - SQLALCHEMY_DATABASE_URI=postgresql://auth_user:auth_pass@auth_db:5432/auth_db
    depends_on:
      - auth_db

volumes:
  auth_db_data:
